export const MIDI_CONTROL_CHANGES = {
    0: 'Bank Select',
    1: 'Modulation wheel',
    2: 'Breath control',
    3: 'Undefined',
    4: 'Foot controller',
    5: 'Portamento time',
    6: 'Data Entry',
    7: 'Channel Volume (formerly Main Volume)',
    8: 'Balance',
    9: 'Undefined',
    10: 'Pan',
    11: 'Expression Controller',
    12: 'Effect control',
    13: 'Effect control',
    14: 'Undefined',
    15: 'Undefined',
    16: 'General Purpose Controller # 1',
    17: 'General Purpose Controller # 2',
    18: 'Standard MIDI file format',
    19: 'General Purpose Controller #3',
    20: 'Undefined',
    21: 'Undefined',
    22: 'Undefined',
    23: 'Undefined',
    24: 'Undefined',
    25: 'Undefined',
    26: 'Undefined',
    27: 'Undefined',
    28: 'Undefined',
    29: 'Undefined',
    30: 'Undefined',
    31: 'Undefined',
    32: 'Bank Select',
    33: 'Modulation wheel',
    34: 'Breath control',
    35: 'Undefined',
    36: 'Foot controller',
    37: 'Portamento time',
    38: 'Data entry',
    39: 'Channel Volume (formerly Main Volume)',
    40: 'Balance',
    41: 'Undefined',
    42: 'Pan',
    43: 'Expression Controller',
    44: 'Effect control',
    45: 'Effect control',
    46: 'Undefined',
    47: 'Undefined',
    48: 'General Purpose Controller # 1',
    49: 'General Purpose Controller # 2',
    50: 'General Purpose Controller # 3',
    51: 'General Purpose Controller # 4',
    52: 'Undefined',
    53: 'Undefined',
    54: 'Undefined',
    55: 'Undefined',
    56: 'Standard MIDI file format',
    57: 'Undefined',
    58: 'Undefined',
    59: 'Undefined',
    60: 'Undefined',
    61: 'Undefined',
    62: 'Undefined',
    63: 'Undefined',
    64: 'Damper pedal on/off (Sustain) <=off >=on',
    65: 'Portamento on/off <=off >=on',
    66: 'Sustenuto on/off <=off >=on',
    67: 'Soft pedal on/off <=off >=on',
    68: 'Legato Footswitch <=off >=on',
    69: 'Hold <=off >=on',
    70: 'Sound Controller (Sound Variation)',
    71: 'Sound Controller (Timbre)',
    72: 'Sound Controller (Release Time)',
    73: 'Sound Controller (Attack Time)',
    74: 'Sound Controller (Brightness)',
    75: 'Sound Controller',
    76: 'Sound Controller',
    77: 'Sound Controller',
    78: 'Sound Controller',
    79: 'Sound Controller',
    80: 'General Purpose Controller # 1',
    81: 'General Purpose Controller # 2',
    82: 'General Purpose Controller # 3',
    83: 'General Purpose Controller # 4',
    84: 'Portamento ControlSource Note',
    85: 'Undefined',
    86: 'Undefined',
    87: 'Undefined',
    88: 'Undefined',
    89: 'Undefined',
    90: 'Undefined',
    91: 'Effects Depth',
    92: 'Effects Depth',
    93: 'Effects Depth',
    94: 'Standard MIDI file format',
    95: 'Effects Depth',
    96: 'Data entry +N/A',
    97: 'Data entry -N/A',
    98: 'Non-Registered Parameter Number',
    99: 'Non-Registered Parameter Number',
    100: 'Registered Parameter Number',
    101: 'Registered Parameter Number',
    102: 'Undefined',
    103: 'Undefined',
    104: 'Undefined',
    105: 'Undefined',
    106: 'Undefined',
    107: 'Undefined',
    108: 'Undefined',
    109: 'Undefined',
    110: 'Undefined',
    111: 'Undefined',
    112: 'Undefined',
    113: 'Undefined',
    114: 'Undefined',
    115: 'Undefined',
    116: 'Undefined',
    117: 'Undefined',
    118: 'Undefined',
    119: 'Undefined',
    120: 'All Sound Off',
    121: 'Reset All Controllers',
    122: 'Local control on/off offon',
    123: 'All notes off',
    124: 'Omni mode off (+ all notes off)',
    125: 'Omni mode on (+ all notes off)',
    126: 'Poly mode on/off (+ all notes off)',
    127: 'Poly mode on (incl mono=off +all notes off)',
} as MidiControlChanges

interface MidiControlChanges {
    [key: number]: string
}
