export const MIDI_INSTRUMENTS = [
    'Acoustic Grand Keyboard',
    'Bright Acoustic Keyboard',
    'Electric Grand Keyboard',
    'Honky-tonk Keyboard',
    'Electric Keyboard',
    'Electric Keyboard 2',
    'Harpsichord',
    'Clavinet',
    'Celesta',
    'Glockenspiel',
    'Music Box',
    'Vibraphone',
    'Marimba',
    'Xylophone',
    'Tubular Bells',
    'Dulcimer (Santur)',
    'Drawbar Organ (Hammond)',
    'Percussive Organ',
    'Rock Organ',
    'Church Organ',
    'Reed Organ',
    'Accordion (French)',
    'Harmonica',
    'Tango Accordion (Band neon)',
    'Acoustic Guitar (nylon)',
    'Acoustic Guitar (steel)',
    'Electric Guitar (jazz)',
    'Electric Guitar (clean)',
    'Electric Guitar (muted)',
    'Overdriven Guitar',
    'Distortion Guitar',
    'Guitar harmonics',
    'Acoustic Bass',
    'Electric Bass (fingered)',
    'Electric Bass (picked)',
    'Fretless Bass',
    'Slap Bass 1',
    'Slap Bass 2',
    'Synth Bass 1',
    'Synth Bass 2',
    'Violin',
    'Viola 1',
    'Cello',
    'Contrabass',
    'Tremolo',
    'Pizzicato',
    'Orchestral Harp',
    'Timpani',
    'String Ensemble 1 (strings)',
    'String Ensemble 2 (slow strings)',
    'SynthStrings 1',
    'SynthStrings 2',
    'Choir Aahs',
    'Voice Oohs',
    'Synth Voice',
    'Orchestra Hit',
    'Trumpet',
    'Trombone',
    'Tuba',
    'Muted Trumpet',
    'French Horn',
    'Brass Section',
    'SynthBrass',
    'SynthBrass 2',
    'Soprano Sax',
    'Alto Sax',
    'Tenor Sax',
    'Baritone Sax',
    'Oboe',
    'English Horn',
    'Bassoon',
    'Clarinet',
    'Piccolo',
    'Flute',
    'Recorder',
    'Pan Flute',
    'Blown Bottle',
    'Shakuhachi',
    'Whistle',
    'Ocarina',
    'Lead 1 (square wave)',
    'Lead 2 (sawtooth wave)',
    'Lead 3 (calliope)',
    'Lead 4 (chiffer)',
    'Lead 5 (charang)',
    'Lead 6 (voice solo)',
    'Lead 7 (fifths)',
    'Lead 8 (bass + lead)',
    'Pad 1 (new age Fantasia)',
    'Pad 2 (warm)',
    'Pad 3 (polysynth)',
    'Pad 4 (choir space voice)',
    'Pad 5 (bowed glass)',
    'Pad 6 (metallic pro)',
    'Pad 7 (halo)',
    'Pad 8 (sweep)',
    'FX 1 (rain)',
    'FX 2 (soundtrack)',
    'FX 3 (crystal)',
    'FX 4 (atmosphere)',
    'FX 5 (brightness)',
    'FX 6 (goblins)',
    'FX 7 (echoes, drops)',
    'FX 8 (sci-fi, star theme)',
    'Sitar',
    'Banjo',
    'Shamisen',
    'Koto',
    'Kalimba',
    'Bag pipe',
    'Fiddle',
    'Shanai',
    'Tinkle Bell',
    'Agogo',
    'Steel Drums',
    'Woodblock',
    'Taiko Drum',
    'Melodic Tom',
    'Synth Drum',
    'Reverse Cymbal',
    'Guitar Fret Noise',
    'Breath Noise',
    'Seashore',
    'Bird Tweet',
    'Telephone Ring',
    'Helicopter',
    'Applause',
    'Gunshot',
] as const

export const MIDI_INSTRUMENTS_FLUIDR3_GM = [
    'acoustic_grand_piano',
    'bright_acoustic_piano',
    'electric_grand_piano',
    'honkytonk_piano',
    'electric_piano_1',
    'electric_piano_2',
    'harpsichord',
    'clavinet',
    'celesta',
    'glockenspiel',
    'music_box',
    'vibraphone',
    'marimba',
    'xylophone',
    'tubular_bells',
    'dulcimer',
    'drawbar_organ',
    'percussive_organ',
    'rock_organ',
    'church_organ',
    'reed_organ',
    'accordion',
    'harmonica',
    'tango_accordion',
    'acoustic_guitar_nylon',
    'acoustic_guitar_steel',
    'electric_guitar_jazz',
    'electric_guitar_clean',
    'electric_guitar_muted',
    'overdriven_guitar',
    'distortion_guitar',
    'guitar_harmonics',
    'acoustic_bass',
    'electric_bass_finger',
    'electric_bass_pick',
    'fretless_bass',
    'slap_bass_1',
    'slap_bass_2',
    'synth_bass_1',
    'synth_bass_2',
    'violin',
    'viola',
    'cello',
    'contrabass',
    'tremolo_strings',
    'pizzicato_strings',
    'orchestral_harp',
    'timpani',
    'string_ensemble_1',
    'string_ensemble_2',
    'synth_strings_1',
    'synth_strings_2',
    'choir_aahs',
    'voice_oohs',
    'synth_choir',
    'orchestra_hit',
    'trumpet',
    'trombone',
    'tuba',
    'muted_trumpet',
    'french_horn',
    'brass_section',
    'synth_brass_1',
    'synth_brass_2',
    'soprano_sax',
    'alto_sax',
    'tenor_sax',
    'baritone_sax',
    'oboe',
    'english_horn',
    'bassoon',
    'clarinet',
    'piccolo',
    'flute',
    'recorder',
    'pan_flute',
    'blown_bottle',
    'shakuhachi',
    'whistle',
    'ocarina',
    'lead_1_square',
    'lead_2_sawtooth',
    'lead_3_calliope',
    'lead_4_chiff',
    'lead_5_charang',
    'lead_6_voice',
    'lead_7_fifths',
    'lead_8_bass__lead',
    'pad_1_new_age',
    'pad_2_warm',
    'pad_3_polysynth',
    'pad_4_choir',
    'pad_5_bowed',
    'pad_6_metallic',
    'pad_7_halo',
    'pad_8_sweep',
    'fx_1_rain',
    'fx_2_soundtrack',
    'fx_3_crystal',
    'fx_4_atmosphere',
    'fx_5_brightness',
    'fx_6_goblins',
    'fx_7_echoes',
    'fx_8_scifi',
    'sitar',
    'banjo',
    'shamisen',
    'koto',
    'kalimba',
    'bagpipe',
    'fiddle',
    'shanai',
    'tinkle_bell',
    'agogo',
    'steel_drums',
    'woodblock',
    'taiko_drum',
    'melodic_tom',
    'synth_drum',
    'reverse_cymbal',
    'guitar_fret_noise',
    'breath_noise',
    'seashore',
    'bird_tweet',
    'telephone_ring',
    'helicopter',
    'applause',
    'gunshot',
] as const

export const MIDI_INSTRUMENTS_MUSYNGKITE = [
    'acoustic_grand_piano',
    'bright_acoustic_piano',
    'electric_grand_piano',
    'honkytonk_piano',
    'electric_piano_1',
    'electric_piano_2',
    'harpsichord',
    'clavinet',
    'celesta',
    'glockenspiel',
    'music_box',
    'vibraphone',
    'marimba',
    'xylophone',
    'tubular_bells',
    'dulcimer',
    'drawbar_organ',
    'percussive_organ',
    'rock_organ',
    'church_organ',
    'reed_organ',
    'accordion',
    'harmonica',
    'tango_accordion',
    'acoustic_guitar_nylon',
    'acoustic_guitar_steel',
    'electric_guitar_jazz',
    'electric_guitar_clean',
    'electric_guitar_muted',
    'overdriven_guitar',
    'distortion_guitar',
    'guitar_harmonics',
    'acoustic_bass',
    'electric_bass_finger',
    'electric_bass_pick',
    'fretless_bass',
    'slap_bass_1',
    'slap_bass_2',
    'synth_bass_1',
    'synth_bass_2',
    'violin',
    'viola',
    'cello',
    'contrabass',
    'tremolo_strings',
    'pizzicato_strings',
    'orchestral_harp',
    'timpani',
    'string_ensemble_1',
    'string_ensemble_2',
    'synth_strings_1',
    'synth_strings_2',
    'choir_aahs',
    'voice_oohs',
    'synth_choir',
    'orchestra_hit',
    'trumpet',
    'trombone',
    'tuba',
    'muted_trumpet',
    'french_horn',
    'brass_section',
    'synth_brass_1',
    'synth_brass_2',
    'soprano_sax',
    'alto_sax',
    'tenor_sax',
    'baritone_sax',
    'oboe',
    'english_horn',
    'bassoon',
    'clarinet',
    'piccolo',
    'flute',
    'recorder',
    'pan_flute',
    'blown_bottle',
    'shakuhachi',
    'whistle',
    'ocarina',
    'lead_1_square',
    'lead_2_sawtooth',
    'lead_3_calliope',
    'lead_4_chiff',
    'lead_5_charang',
    'lead_6_voice',
    'lead_7_fifths',
    'lead_8_bass__lead',
    'pad_1_new_age',
    'pad_2_warm',
    'pad_3_polysynth',
    'pad_4_choir',
    'pad_5_bowed',
    'pad_6_metallic',
    'pad_7_halo',
    'pad_8_sweep',
    'fx_1_rain',
    'fx_2_soundtrack',
    'fx_3_crystal',
    'fx_4_atmosphere',
    'fx_5_brightness',
    'fx_6_goblins',
    'fx_7_echoes',
    'fx_8_scifi',
    'sitar',
    'banjo',
    'shamisen',
    'koto',
    'kalimba',
    'bagpipe',
    'fiddle',
    'shanai',
    'tinkle_bell',
    'agogo',
    'steel_drums',
    'woodblock',
    'taiko_drum',
    'melodic_tom',
    'synth_drum',
    'reverse_cymbal',
    'guitar_fret_noise',
    'breath_noise',
    'seashore',
    'bird_tweet',
    'telephone_ring',
    'helicopter',
    'applause',
    'gunshot',
] as const

export const MIDI_INSTRUMENTS_FATBOY = [
    'acoustic_grand_piano',
    'bright_acoustic_piano',
    'electric_grand_piano',
    'honkytonk_piano',
    'electric_piano_1',
    'electric_piano_2',
    'harpsichord',
    'clavinet',
    'celesta',
    'glockenspiel',
    'music_box',
    'vibraphone',
    'marimba',
    'xylophone',
    'tubular_bells',
    'dulcimer',
    'drawbar_organ',
    'percussive_organ',
    'rock_organ',
    'church_organ',
    'reed_organ',
    'accordion',
    'harmonica',
    'tango_accordion',
    'acoustic_guitar_nylon',
    'acoustic_guitar_steel',
    'electric_guitar_jazz',
    'electric_guitar_clean',
    'electric_guitar_muted',
    'overdriven_guitar',
    'distortion_guitar',
    'guitar_harmonics',
    'acoustic_bass',
    'electric_bass_finger',
    'electric_bass_pick',
    'fretless_bass',
    'slap_bass_1',
    'slap_bass_2',
    'synth_bass_1',
    'synth_bass_2',
    'violin',
    'viola',
    'cello',
    'contrabass',
    'tremolo_strings',
    'pizzicato_strings',
    'orchestral_harp',
    'timpani',
    'string_ensemble_1',
    'string_ensemble_2',
    'synth_strings_1',
    'synth_strings_2',
    'choir_aahs',
    'voice_oohs',
    'synth_choir',
    'orchestra_hit',
    'trumpet',
    'trombone',
    'tuba',
    'muted_trumpet',
    'french_horn',
    'brass_section',
    'synth_brass_1',
    'synth_brass_2',
    'soprano_sax',
    'alto_sax',
    'tenor_sax',
    'baritone_sax',
    'oboe',
    'english_horn',
    'bassoon',
    'clarinet',
    'piccolo',
    'flute',
    'recorder',
    'pan_flute',
    'blown_bottle',
    'shakuhachi',
    'whistle',
    'ocarina',
    'lead_1_square',
    'lead_2_sawtooth',
    'lead_3_calliope',
    'lead_4_chiff',
    'lead_5_charang',
    'lead_6_voice',
    'lead_7_fifths',
    'lead_8_bass__lead',
    'pad_1_new_age',
    'pad_2_warm',
    'pad_3_polysynth',
    'pad_4_choir',
    'pad_5_bowed',
    'pad_6_metallic',
    'pad_7_halo',
    'pad_8_sweep',
    'fx_1_rain',
    'fx_2_soundtrack',
    'fx_3_crystal',
    'fx_4_atmosphere',
    'fx_5_brightness',
    'fx_6_goblins',
    'fx_7_echoes',
    'fx_8_scifi',
    'sitar',
    'banjo',
    'shamisen',
    'koto',
    'kalimba',
    'bagpipe',
    'fiddle',
    'shanai',
    'tinkle_bell',
    'agogo',
    'steel_drums',
    'woodblock',
    'taiko_drum',
    'melodic_tom',
    'synth_drum',
    'reverse_cymbal',
    'guitar_fret_noise',
    'breath_noise',
    'seashore',
    'bird_tweet',
    'telephone_ring',
    'helicopter',
    'applause',
    'gunshot',
] as const

export const DRUM_KIT = {
    35: 'Acoustic Bass Drum',
    59: 'Ride Cymbal 2',
    36: 'Bass Drum 1',
    60: 'Hi Bongo',
    37: 'Side Stick',
    61: 'Low Bongo',
    38: 'Acoustic Snare',
    62: 'Mute Hi Conga',
    39: 'Hand Clap',
    63: 'Open Hi Conga',
    40: 'Electric Snare',
    64: 'Low Conga',
    41: 'Low Floor Tom',
    65: 'High Timbale',
    42: 'Closed Hi Hat',
    66: 'Low Timbale',
    43: 'High Floor Tom',
    67: 'High Agogo',
    44: 'Pedal Hi-Hat',
    68: 'Low Agogo',
    45: 'Low Tom	',
    69: 'Cabasa',
    46: 'Open Hi-Hat',
    70: 'Maracas',
    47: 'Low-Mid Tom',
    71: 'Short Whistle',
    48: 'Hi Mid Tom',
    72: 'Long Whistle',
    49: 'Crash Cymbal 1	',
    73: 'Short Guiro',
    50: 'High Tom',
    74: 'Long Guiro',
    51: 'Ride Cymbal 1',
    75: 'Claves',
    52: 'Chinese Cymbal	',
    76: 'Hi Wood Block',
    53: 'Ride Bell',
    77: 'Low Wood Block',
    54: 'Tambourine',
    78: 'Mute Cuica',
    55: 'Splash Cymbal',
    79: 'Open Cuica',
    56: 'Cowbell',
    80: 'Mute Triangle',
    57: 'Crash Cymbal 2',
    81: 'Open Triangle',
    58: 'Vibraslap',
} as const
