export const MIDI_CONTROL_CHANGES = [
    'Bank Select',
    'Modulation wheel',
    'Breath control',
    'Undefined',
    'Foot controller',
    'Portamento time',
    'Data Entry',
    'Channel Volume (formerly Main Volume)',
    'Balance',
    'Undefined',
    'Pan',
    'Expression Controller',
    'Effect control',
    'Effect control',
    'Undefined',
    'Undefined',
    'General Purpose Controller # 1',
    'General Purpose Controller # 2',
    'Standard MIDI file format',
    'General Purpose Controller #3',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Bank Select',
    'Modulation wheel',
    'Breath control',
    'Undefined',
    'Foot controller',
    'Portamento time',
    'Data entry',
    'Channel Volume (formerly Main Volume)',
    'Balance',
    'Undefined',
    'Pan',
    'Expression Controller',
    'Effect control',
    'Effect control',
    'Undefined',
    'Undefined',
    'General Purpose Controller # 1',
    'General Purpose Controller # 2',
    'General Purpose Controller # 3',
    'General Purpose Controller # 4',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Standard MIDI file format',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Damper pedal on/off (Sustain) <=off >=on',
    'Portamento on/off <=off >=on',
    'Sustenuto on/off <=off >=on',
    'Soft pedal on/off <=off >=on',
    'Legato Footswitch <=off >=on',
    'Hold <=off >=on',
    'Sound Controller (Sound Variation)',
    'Sound Controller (Timbre)',
    'Sound Controller (Release Time)',
    'Sound Controller (Attack Time)',
    'Sound Controller (Brightness)',
    'Sound Controller',
    'Sound Controller',
    'Sound Controller',
    'Sound Controller',
    'Sound Controller',
    'General Purpose Controller # 1',
    'General Purpose Controller # 2',
    'General Purpose Controller # 3',
    'General Purpose Controller # 4',
    'Portamento ControlSource Note',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Effects Depth',
    'Effects Depth',
    'Effects Depth',
    'Standard MIDI file format',
    'Effects Depth',
    'Data entry +N/A',
    'Data entry -N/A',
    'Non-Registered Parameter Number',
    'Non-Registered Parameter Number',
    'Registered Parameter Number',
    'Registered Parameter Number',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'Undefined',
    'All Sound Off',
    'Reset All Controllers',
    'Local control on/off offon',
    'All notes off',
    'Omni mode off (+ all notes off)',
    'Omni mode on (+ all notes off)',
    'Poly mode on/off (+ all notes off)',
    'Poly mode on (incl mono=off +all notes off)',
]
