# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - vitzik

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          
      - name: Install Corepack
        run: npm i -g corepack
      
      - name: Enable Corepack (Yarn 4+)
        run: corepack enable
      
      - name: Use the Correct Yarn Version
        run: corepack prepare yarn@4.2.2 --activate

      - name: yarn install, build, and test
        run: |
          yarn
          yarn build 
          yarn test

      - name: Zip artifact for deployment
        run: | 
          cd ./packages/vitzik-app/dist
          zip -r ../../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_75A9238A907440E285F7C27275D97749 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_11DAE5E9AA8F4AD4A6D6ACC596F50C8C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21E0FCECA8734C79BA33E55CFBFDCBD0 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vitzik'
          slot-name: 'Production'
          package: .
          
